Sprint 1
Nilfan/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-07 14:58 UTC by Nilfan

2021-07-07 21:14 UTC, avdoshenkov requested changes
Отлично поработал! Осталось только несколько нюансов поправить, и будет идеально.

Ещё заметил, что по заданию не хватает страницы с мессенджером (хотя бы заглушки), а также полей для смены пароля
<img width="676" alt="Снимок экрана" src="https://user-images.githubusercontent.com/26881016/124829579-d9a64c00-df89-11eb-936d-bb3b314f8dfc.png">

2021-07-07 21:14 UTC, avdoshenkov commented on .gitignore
> +// build
В `.gitignore` комментарии начинаются не как в JS, а со знака `#`

2021-07-07 21:14 UTC, avdoshenkov commented on README.md
> +## Usage
В самом начале будет круто, если добавишь описание и название проекта — что это вообще за репозиторий и для чего. А потом уже да, можно про запуск рассказать.

2021-07-07 21:14 UTC, avdoshenkov commented on server.js
> +const PORT = 3000;
Здесь можно порт указать таким образом:
```
const PORT = process.env.PORT || 3000; 
```
Тогда будет возможность брать значение из env переменных, а уже если там её не окажется, то брать значение по умолчанию

2021-07-07 21:14 UTC, avdoshenkov commented on src/pages/login-page/login-page.tmpl.js
> +          <input class="text-input invalid" name="login" placeholder="Логин"/>
По хорошему у каждого инпута должен быть свой лейбл. Это и с точки зрения семантики, и доступности будет полезно, да и пользователю удобно. Конкретно данный макет, конечно, подталкивает использовать placeholder, но всё же это не лучшее решение. Подробнее можно почитать [тут](https://www.htmhell.dev/24-a-placeholder-is-not-a-label/)

2021-07-07 21:14 UTC, avdoshenkov commented on src/pages/signin-page/signin-page.tmpl.js
> +export const signinPageTmpl = `
`Sign in` — это всё же имеется ввиду вход обычно, а для регистрации — `Sign up`

2021-07-07 21:14 UTC, avdoshenkov commented on src/pages/signin-page/signin-page.tmpl.js
> +          <button class="btn btn-cancel"> Войти </button>
Здесь скорее всего по смыслу больше подходит ссылка, т.к. по клику нас должно перекинуть на отдельную страницу со входом. Это достаточно [распространённая штука](https://www.htmhell.dev/5-button-like-link/), которую лучше избегать

2021-07-07 21:14 UTC, avdoshenkov commented on src/styles/common-style.scss
> +$main-blue: #3587be;
Конкретно этот файл, кажется, можно переименовать в `variables.scss`. По смыслу будет логичнее. 

В `common` обычно какие-то классы записывают, которые по системе в разных местах будут использоваться, по типу тех, что уже в `style.scss` определены

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +function identity(param) {
Не совсем понял смысл этой функции

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +  let length = Math.max(Math.ceil((end - start) / (step || 1)), 0);
```suggestion
const baseRange = (start, end, step = 1, isRight) => {
  let index = -1;
  let length = Math.max(Math.ceil((end - start) / step), 0);
```
Значение по умолчанию лучше вынести сюда, т.к. дальше в цикле тоже используется переменная `step` и если она не определена, то результат выполнения будет не тем, что мы ожидаем

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +  let length = Math.max(Math.ceil((end - start) / (step || 1)), 0);
Имя аргумента `isRight` не совсем очевидное. В данном случае его лучше назвать как-то вроде `hasReverseOrder` или что-то подобное

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +function rangeRight(start, end, step) {
Эту функцию тоже лучше назвать по типу `reversedRange` или `descendingRange`

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +  if (obj == null) {
Раз мы проверяем и `undefined`, то можно использовать созданную функцию `isNil`

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +    if (hasOwnProperty.call(value, key)) {
Можно просто:
```suggestion
    if (value.hasOwnProperty(key)) {
```

2021-07-07 21:14 UTC, avdoshenkov commented on src/utils/helpers.js
> +      isTypedArray(value) ||
Эти две функции не определены

2021-07-07 21:14 UTC, avdoshenkov commented on src/pages/user-profile/user-profile.js
> +    const raws = this.generateUserInfoRows(ctx)
Наверное, имелось в виду `rows`

2021-07-08 20:04 UTC, Nilfan commented on .gitignore
> +// build
Done

2021-07-08 20:04 UTC, Nilfan commented on README.md
> +## Usage
Done

2021-07-08 20:05 UTC, Nilfan commented on server.js
> +const PORT = 3000;
Done

2021-07-08 20:05 UTC, Nilfan commented on src/pages/login-page/login-page.tmpl.js
> +          <input class="text-input invalid" name="login" placeholder="Логин"/>
Done

2021-07-08 20:05 UTC, Nilfan commented on src/pages/signin-page/signin-page.tmpl.js
> +export const signinPageTmpl = `
Fixed

2021-07-08 20:05 UTC, Nilfan commented on src/styles/common-style.scss
> +$main-blue: #3587be;
File renamed

2021-07-08 20:05 UTC, Nilfan commented on src/utils/helpers.js
> +function identity(param) {
Function were deleted

2021-07-08 20:06 UTC, Nilfan commented on src/utils/helpers.js
> +  let length = Math.max(Math.ceil((end - start) / (step || 1)), 0);
Argument renamed

2021-07-08 20:06 UTC, Nilfan commented on src/utils/helpers.js
> +function rangeRight(start, end, step) {
Also renamed

2021-07-08 20:06 UTC, Nilfan commented on src/utils/helpers.js
> +  if (obj == null) {
Done

2021-07-08 20:06 UTC, Nilfan commented on src/utils/helpers.js
> +    if (hasOwnProperty.call(value, key)) {
Suggestion applied

2021-07-08 20:10 UTC, Nilfan commented on src/utils/helpers.js
> +      isTypedArray(value) ||
Both functions were deleted

2021-07-08 20:10 UTC, Nilfan commented on src/pages/user-profile/user-profile.js
> +    const raws = this.generateUserInfoRows(ctx)
Fixed

2021-07-08 20:10 UTC, Nilfan commented on src/pages/signin-page/signin-page.tmpl.js
> +          <button class="btn btn-cancel"> Войти </button>
Fixed

2021-07-09 04:52 UTC, avdoshenkov approved these changes
Всё супер, молодцом! Можно двигаться дальше

2021-07-09 04:52 UTC, avdoshenkov commented on src/components/user-info-table/user-info-table.tmpl.js
> +          <div class="raw-value"> {{this.value}} </div>
Здесь можно использовать [Description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl). Это просто на будущее)

2021-07-09 06:33 UTC, Nilfan commented on src/components/user-info-table/user-info-table.tmpl.js
> +          <div class="raw-value"> {{this.value}} </div>
Полезно, запомню)

2021-07-24 09:02 UTC, merged