Add linters - stylelint, eslint
Nilfan/middle.messenger.praktikum.yandex pull request #4
Opened 2021-07-27 19:56 UTC by Nilfan

Add tsconfig
Add components: avatar-image, back-button-column, chats-list with its item component, form-field, message-table
Add input and form validation
Move all js-files to ts-extension

2021-07-28 12:20 UTC, nickchamel requested changes
Привет. В целом все отлично, я оставил тебе рекомендации в комментариях. Но работу я вынужден вернуть. Не работают след. страницы:
/signin
/change-user-profile
/change-user-password
/messenger
Вообще signin и login это одно и то же, обычно либо login/registration либо signin/signup.

2021-07-28 12:20 UTC, nickchamel commented on .stylelintrc.json
> +  "ignoreFiles": ["src/styles/variables.scss", "dist/**/*.css"],
src стили не должны быть в игноре

2021-07-28 12:20 UTC, nickchamel commented on index.ts
> +);
Тут можно проще
В getRoute
```
export function getRoute(path: string) {
  return routes.find((route) => route.path === path) || defaultPageRoute;
}
```
и тогда можно проще написать
```
const pageMeta = getRoute(window.location.pathname);
```
не нужен ни hasRoute, ни defaultPageName
Это одна из задач роутера - обработкой таких кейсов.
А вот чем роутер не должен заниматься - так это созданием чилдренов для страниц, этим должны заниматься сами страницы, об этом позже

2021-07-28 12:20 UTC, nickchamel commented on src/components/chats-list-item/chats-list-item.tmpl.ts
> +      </div>
неплохо бы шаблоны привети к одному виду (отступы и тп)

2021-07-28 12:20 UTC, nickchamel commented on src/components/chats-list-item/chats-list-item.ts
> +import * as Handlebars from "handlebars";
лучше импорты из node_modules и src держать отдельно, проще ориентироваться. К примеру - сначала импорты из node_modules, потом из src, некоторые еще между ними делают отступ

2021-07-28 12:20 UTC, nickchamel commented on src/components/chats-list-item/chats-list-item.ts
> +});
А что если этот хелпер понадобиться в каком-нибудь шаблоне, но данный компонент не будет присутсвовать на странице, то есть его импорта тоже не будет. И соответсвенно этот хелпер не зарегистрируеться.
Для хелперов лучше использовать отдельный файл и импортить его там, где нужен какой-либо хелпер
`import '../../helpers/helpers.ts'`

2021-07-28 12:20 UTC, nickchamel commented on src/components/chats-list/chats-list.ts
> +import {} from "../chats-list-item/chats-list-item";
можно удалить видимо

2021-07-28 12:20 UTC, nickchamel commented on src/components/chats-list/chats-list.ts
> +  }
Ты можешь в конструкторе создать чилдренов, можешь в рендере, можешь вообще вынести наверх этого файла создание чилдренов, но ты почему-то их создаешь в роутах. У тебя роуты слишком много знают, это не их задача, создавать чилдренов, роуты должны просто сопоставить pathname и с каким-то компонентом, а дальше уже при создании этого компонента будут создаваться его чилдрены (им самим). И в один момент времени будет создана одна страница и только необходимые для нее чилдрены. А у тебя сейчас получается так, что на старте приложения, не важно на какой странице мы нахоимся - создаются всевозможные чилдрены для всех страниц и висят в памяти, но не используются

2021-07-28 12:20 UTC, nickchamel commented on src/components/message-table/message-table.ts
> +      currentUserMessage: message.userId === props.currentUserId,
такие поля лучше называть что-то типа `isCurrentUserMessage`, потому что у тебя есть массив сообщений и в некоторых из них ты создаешь поле `сообщение`. Флаг `is` как бы говорит о том, что является ли это конкретное сообщение чем-то или удовлетворяет чему-то

2021-07-28 12:20 UTC, nickchamel commented on src/components/tables/change-user-info-table/change-user-info-table.tmpl.ts
> +//           <LoginInput></LoginInput>
такие комментарии лучше удалять, дабы не засорять код

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/classes/request-service.ts
> +export function fetch(url: string, options: RequestOptions) {
Давай доработаем. По заданию - `Реализуйте методы GET, POST, PUT, DELETE;`

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/helpers.ts
> +function get(obj: Object, path: string, defaultValue: string | number | null | undefined) {
undefined можно не встраивать в цепочку, для него можно использовать `?`.
`defaultValue?: string | number | null`, некоторые IDE только так и смогут "перехватить" опциональный параметр

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/helpers.ts
> +  let result: { [key: string]: any } = obj;
или Record<string, any>. часто встречающийся тип данных, можно его вынести в глобальные типы, называют его обычно `ObjectLiteral`

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/helpers.ts
> +function first(list: any) {
по твоему коду я вижу что все-таки это должен быть массив, либо его может не быть, значит `list?: []`, а лучше конкретно типизированный array

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/validation/form-validation.ts
> +      }
как правило, такие ошибки отлавливают еще на этапе разработки и для них не нужно писать такие проверки, а вот если по какой-либо причине это произойдет в продакшене, то такие ошибки просто "повалят" приложение. С этим нужно быть осторожнее

2021-07-28 12:20 UTC, nickchamel commented on src/helpers/validation/form-validation.ts
> +}
Не совсем понимаю как связана валидация филда и листенеры на элементе. Listener это то, что происходит например при клике, сабмите, а валидация это например введенный текст в инпут должен соответсвовать какому-то regExp или быть максимум 30 символов длинной и тп (ну собственно дальше по коду они у тебя и идут)
Тут ты еще имитируешь ивент к тому же. Лучше так не делать. Либо как минимум ты должен типизировать это дело. И у тебя в листенер может приходить нормальный ивент либо заглушка с таргетом. Но опять же лучше так вообще не делать

2021-07-29 08:46 UTC, Nilfan commented on .stylelintrc.json
> +  "ignoreFiles": ["src/styles/variables.scss", "dist/**/*.css"],
Done

2021-07-29 08:46 UTC, Nilfan commented on index.ts
> +);
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/chats-list-item/chats-list-item.tmpl.ts
> +      </div>
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/chats-list-item/chats-list-item.ts
> +import * as Handlebars from "handlebars";
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/chats-list-item/chats-list-item.ts
> +});
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/chats-list/chats-list.ts
> +import {} from "../chats-list-item/chats-list-item";
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/chats-list/chats-list.ts
> +  }
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/message-table/message-table.ts
> +      currentUserMessage: message.userId === props.currentUserId,
Done

2021-07-29 08:46 UTC, Nilfan commented on src/components/tables/change-user-info-table/change-user-info-table.tmpl.ts
> +//           <LoginInput></LoginInput>
Done

2021-07-29 08:47 UTC, Nilfan commented on src/helpers/classes/request-service.ts
> +export function fetch(url: string, options: RequestOptions) {
Done

2021-07-29 08:47 UTC, Nilfan commented on src/helpers/helpers.ts
> +  let result: { [key: string]: any } = obj;
Done

2021-07-29 08:47 UTC, Nilfan commented on src/helpers/helpers.ts
> +function first(list: any) {
Done

2021-07-29 08:47 UTC, Nilfan commented on src/helpers/validation/form-validation.ts
> +      }
Done

2021-07-29 08:47 UTC, Nilfan commented on src/helpers/validation/form-validation.ts
> +}
Done

2021-07-29 14:51 UTC, nickchamel commented
Хорошо! Работа принята. Успехов в след. спринте.

2021-07-29 15:56 UTC, merged